# -- terminal -------------------------------------------------------------------
set -g default-terminal "screen-256color"

set -s focus-events on
set -g set-clipboard on

set -s extended-keys always
set -s extended-keys-format csi-u
set -as terminal-features ',xterm-ghostty:extkeys'

# -- general --------------------------------------------------------------------
set -q -g status-utf8 on
setw -q -g utf8 on

set -s escape-time 10
set -sg repeat-time 600
set -g history-limit 5000

unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g status-keys emacs
bind r source-file "$XDG_CONFIG_HOME/tmux/tmux.conf" \; display-message "tmux config reloaded"

# -- display --------------------------------------------------------------------
set -g base-index 1
set -g pane-base-index 1
set -g mouse on
set -g set-titles on

# -- navigation -----------------------------------------------------------------
unbind %
bind _ split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind > swap-pane -D
bind < swap-pane -U

bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

bind Tab last-window

# -- copy mode ------------------------------------------------------------------
set-window-option -g mode-keys vi

bind Enter copy-mode
bind -T copy-mode-vi Escape send -X cancel
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# -- plugins --------------------------------------------------------------------
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$XDG_DATA_HOME/tmux/plugins/"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'timvw/tmux-assistant-resurrect'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

if-shell 'test -f "$XDG_DATA_HOME/tmux/plugins/tpm/tpm"' 'run-shell "$XDG_DATA_HOME/tmux/plugins/tpm/tpm"'
